### ISSUE TITLE
Profile of State Admin

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1036]
When a state admin logs in, he cannot see any info in the profile tab

Also, updating personal information is not possible

Username: state-admin
Password: Lilo@123
(On staging)

**Comment by Sandra3657** [comment]
![image](https://user-images.githubusercontent.com/62461536/117662880-ae87c200-b1bd-11eb-9b5a-1c87e653bda2.png)
This is on the staging and the profile looks fine and we are also able to edit it. @aparnacoronasafe

**Comment by aparnacoronasafe** [comment]
Please try this user id on staging. The issue persists for me. 
Syam
tomahawk@T1

<img width="1430" alt="Screenshot 2021-05-11 at 4 38 05 PM" src="https://user-images.githubusercontent.com/67050716/117806298-c3289080-b277-11eb-9d32-a85663eb29ae.png">

@sam9111 
@Sandra3657

**Comment by Sandra3657** [comment]
We have went through the code and tested the api. It turns out that the details for the user is already present. But the api used for getting the details **`(/users/{username}/)`**, returns ''details not found error''. There seems to some sort of restriction for the stateleveladmin to access his own details using this api.

Can you pls look into it? @vigneshhari

**Comment by vigneshhari** [comment]
@divyagar find out what is happening here.

**Comment by divyagar** [comment]
@vigneshhari  The error is due to this line : `queryset = User.objects.filter(is_superuser=False).select_related("local_body", "district", "state")`.
Is there any reason to filter users on the basis of `is_superuser` field?

**Comment by vigneshhari** [comment]
Admins are not queryable by any API's. Lets keep it that way, it should not be related to a stateadmin issue.

**Comment by divyagar** [comment]
@vigneshhari I have tried it many time with different users and removing filter is working fine. The reason is that due to filter `queryset` does not contain any superuser. In `retrieve` function, one of the object present in `queryset` is returned. But there is no superuser in `queryset` that's why `Detail not found` error is shown.
If we cannot remove the filter, then I think we would have to override `retrieve` function to fetch user data directly from serializer.

**Comment by bodhish** [comment]
@aparnacoronasafe super admins accounts are not created to access the FE. We took a decision to hide that a while back. 

In my understanding, `tomahawk@T1` is a super admin and the account details will not be accessible in the FE.
