### ISSUE TITLE
A new tele-medicine doc cannot be assigned

### ISSUE THREAD

**Issue by amruthavijay88** [ohcnetwork/care_fe#1353]
When I am assigning a patient to a new tele-medicine doctor, the field automatically clears doctor's name. Unable to assign it the doctor. 
For eg; Try assigning to Dr. Nazia Ali in staging.

**Comment by khavinshankar** [comment]
@vigneshhari need a new paramater `id` in `GET /users/` `(api/v1/users/)`

**Comment by vigneshhari** [comment]
@khavinshankar this feature was working for close to 10 months, why is it breaking now? also, the id is already present in the API, did you check the swagger docs?

**Comment by khavinshankar** [comment]
@vigneshhari 
Currently, we have more than 30 doctors but before we had only about 15 (less than 30) in staging, this is the cause of the issue,
As of now, the flow goes like this,
 - the DoctorSelector component receives `userId` as props,
 - the `fetchUser` function fetches the first 30 doctors,
 - `selectedDoctors = users.find((user) => user.id === userId )`

So before it worked fine because the doctor was always on the fetched list.

and, there is username but no id(userId) in GET /users/ (api/v1/users/)
![image](https://user-images.githubusercontent.com/29787772/120959093-a39d5e80-c776-11eb-92a4-b57f50c18476.png)

**Comment by vigneshhari** [comment]
I still don't understand the issue, the id is in the API, right?

**Comment by vigneshhari** [comment]
Also create another issue to paginate this endpoint.

**Comment by khavinshankar** [comment]
> I still don't understand the issue, the id is in the API, right?

The id is not in the API, 
found a workaround without the need for id.
