### ISSUE TITLE
Preview in not working in Patient Files

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/care_fe#1486]
![ef fwf pefo](https://user-images.githubusercontent.com/57055998/123521491-8eac4f00-d6d4-11eb-8743-505360bb6c05.JPG)

when we are uploading a .jpeg file into the 'View/ Upload patient files' inside a patient card the preview is not working  but we are able to download the file

**Comment by khavinshankar** [comment]
@nihal467 this feature is working fine in localhost (when run locally) and netlify deploy versions (testing deploys in PRs). I think the problem is in where the staging is deployed

working on localhost:
![image](https://user-images.githubusercontent.com/29787772/123531897-fa6ad800-d725-11eb-975d-c1b242cba85e.png)

working on netlify deploys:
![image](https://user-images.githubusercontent.com/29787772/123531934-2dad6700-d726-11eb-89e2-dbe884f0017b.png)

@bodhish can you please look this up!

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/52771399/123548362-1e5c0700-d782-11eb-949b-10bb86e434aa.png)

Hmm CORS error @bodhish

**Comment by peeyush14goyal** [comment]
Why is there a difference between netlify version and deployed version ? @bodhish

**Comment by bodhish** [comment]
Yes, our server has strict cors policy.
Means any javascript that's not served / whitelisted by us can't be executed in run time. 

@tomahawk-pilot can you check out the issue

**Comment by bodhish** [comment]
The CORS issue is now fixed
