### ISSUE TITLE
Report on daily hospitalisation

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1787]
The state required details of hospitalisation across various bed types (i.e. home isolation, normal bed, oxygen bed, ICU, Ventilator) for any PARTICULAR DATE.

The report must also have granular data on how many of such patients are:
- Vaccinated (none, 1st dose, both doses)
- age 
- gender 

**flaw with the current system**
In the current patient list, the users tried to add the following filters to fetch the data of hospitalisation for a particular date. 
- Admitted to date range is set to that date.
- Admitted to bed type is set one by one
- Vaccination filter to get the vaccination details
But the issue with this method is that when trying to retrieve data of past date, the "admitted to-bedtype" filter only scans the last consultation for any patient to get the "admitted to - bedtype" information. Then, if a patient was admitted in an ICU a week back, and subsequently upon recovery moved to a normal bed, his data wouldnt show up in last weeks ICU admissions.

Hence the reports going to the state now has inadequate data.

@gigincg Please let me know if you require further explanation.

**Comment by gigincg** [comment]
https://github.com/coronasafe/care/issues/674

**Comment by aparnacoronasafe** [comment]
@nihal467 Have you tested this?

You need to specifically focus on the following usecases:

1) Patient A is admitted to a normal bed from 1-10 Mar and an ICU FROM 10-15 MAR AND BACK IN A NORMAL BED FROM 15-20TH MAR. 
Add filter to patent list to get all patient:
a) admitted in normal bed on 8th March
b) Admitted in normal bed on 13th March
c) Admitted in ICU bed on 5th March
d) Admitted in ICU bed on 11th March

Also see if these can be combined with Age / Gender/ Vaccine filters.

**Comment by nihal467** [comment]
@aparnacoronasafe the bug persists, and when won't be able to generate a report for the use case you mentioned, we can only filter patients with their initial admission details and not with the latest bed swapped details

**Comment by nihal467** [comment]
@aparnacoronasafe 

https://care.coronasafe.in/facility/53a7266a-ed34-4616-85eb-7ae1be57d2cc/patient/4ae3b7de-800d-4b41-8ac9-00dbb741fe9f/consultation/54959916-9496-49ea-9ebe-e1ff579e5557

![image](https://user-images.githubusercontent.com/57055998/226821072-3e58f58d-6d6c-4fd0-a9fd-9b8856e67541.png)

**Issue: 1** 

A Patient named "Test-daily-hospitalreport" in the facility "test-march-thirdweek" was initially admitted to the hospital
- on 01/03/2023 to a regular bed
- later on 10/03/2023 he was shifted from a regular bed to icu.
- again on 15/03/2023 he was again shifted back to a regular bed.

When we go to the patient tab, apply a filter, admitted to "regular", it generates a list of all the patients in the regular bed, by looking at their current bed status, we are not able to apply a filter to see, which all patients were admitted in a regular bed, for the period 08/03/2022 to 14/03/2022 because 

1. the admit date filter in the advance filter, is only checking the initial admit date of the patient and not the bed change date of the patient
2. we are not able to use advance filter in the patient tab, to check past bed types used by a patient for a period of date and time

**Edge Case in this issue**: If a patient is shifted from a regular bed to icu bed on the 10th of march and we generate a specific individual report for the 10th march of the patients in regular bed and icu, the report will be double counting a patient, so we should be adding time to the filter along with the date.

**Comment by nihal467** [comment]
feature: Search by encounters or consultations 
feature: Search by admission
-> dedicated page for the feature

**Comment by nihal467** [comment]
The issue will be resolved by two new features in the platform, the request is been filed, so closing this issue.
