### ISSUE TITLE
Facility: Admission data

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#1789]
Any facility today cannot fetch data on how many admissions they have had on any day.

The problem is even if they apply the admissions date filters, they can browse through the live list/dischasrged list of patients, but they will not have details or number of patients who were admitted to their facility on such date and they discharged and admitted to / shifted to another facility.

Every facility must have its own registry of a number of admissions across various bed types. 

@gigincg

**Comment by aparnacoronasafe** [comment]
Admission of a patient needs to be identified in the system as a period in time, rather than a point in time. This will allow the admission date filter to show data of patients on a particular day, even if the admission itself happened a day ago.

**Comment by aparnacoronasafe** [comment]
The issue is, if there is a patient admitted in a hospital from 5th to 15th of a month, the user must be able to fetch admission list of any particular day, 10th. This patients records must also come up.

**Comment by ishanExtreme** [comment]
@aparnacoronasafe We need to add an extra filter in "Advance Filter" section of the patients tab which can instead of date range take a single date and search all patients that were in the hospital at that date?, something like in the image below? 

![Screenshot from 2022-06-29 20-59-54](https://user-images.githubusercontent.com/39593226/176476944-1326b767-0b4f-4516-888b-337069a2094a.png)

**Comment by aparnacoronasafe** [comment]
Hey @ishanExtreme any progress on this?

**Comment by khavinshankar** [comment]
@aparnacoronasafe @ishanExtreme Instead of adding a new field for `Admit Date` in the `Advanced Filters` like
![Screenshot from 2022-06-29 20-59-54](https://user-images.githubusercontent.com/39593226/176476944-1326b767-0b4f-4516-888b-337069a2094a.png)
why don't we just use the existing `Admit Date` field, we can set both `from` and `to` dates to the same date to achieve the behavior we want
![image](https://user-images.githubusercontent.com/29787772/184655560-c098dc4a-b730-4a11-a5c2-3a335b215998.png)
