### ISSUE TITLE
Notification for file upload

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#899]
Notification to show for file uploads also

**Comment by bodhish** [comment]
@aparnacoronasafe could explain why this is required 🤔

**Comment by aparnacoronasafe** [comment]
The notification feature became a requirement only when we started having the panel of doctors at PVS remotely monitoring patients amitted in other facilities like SLTCs. 

So now a patient admitted in Facility A may be under the supervision of the PVS Doctor. Naturally every consultation/consultation update filed by the Facility A staff or the PVS doc needs to come into the attantion of both these parties. 

Now, silimarly, the file upload is another way by which the facility A staff will be logging clinical details of the patient. Say, a chest X-ray of the patient is uploaded. Unless the PVS doc gets a notification of the same, it may go un-noticed. 

@vigneshhari Please comment

**Comment by vigneshhari** [comment]
We can show an intimation that the file upload has started , but we cannot for sure say that a file has been uploaded successfully because the server never knows that.

**Comment by aparnacoronasafe** [comment]
@vigneshhari lets have that then.:-)

**Comment by bodhish** [comment]
@aparnacoronasafe This may not be the right solution for the problem that you have mentioned. 

The notification feature is more generic and is designed to trigger notification for events that needs the attention of all parties involved.

This is more like a controlled alert to a specific set of user class for a custom event. 

File upload is an alpha feature which is yet to go live on the field, let it go live and let's evaluate the pain points. 

@vigneshhari I understand that a few changes could be enough to stuff this inside the notifications mechanism but let's not do it since we don't have clarity. 

Let's not create notifications unless it's super required. I really don't want care to spam people.
