### ISSUE TITLE
Lakshadweep Shifting UI Change

### ISSUE THREAD

**Issue by aparnacoronasafe** [ohcnetwork/care_fe#931]
https://care.coronasafe.network/shifting

Please make the cards from other states appear in a different colour on the shifting dashboard.

**Comment by smartclash** [comment]
Since the card changes to red color if the patient is tested positive for corona, I don't think it would be a good idea to change the color to something else for different state.

What if we just show which state the patient belongs to in the card itself? Something like this...
![image](https://user-images.githubusercontent.com/16922883/116776851-79c28f00-aa88-11eb-8b3a-7c010127dc43.png)

**Comment by vigneshhari** [comment]
@aparnacoronasafe, @smartclash has a valid point there.
